# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.3'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'activeadmin'
gem 'draper', '~> 4.0', '>= 4.0.1'
gem 'pg', '~> 1.5'
gem 'flipper', '~> 1.2', '>= 1.2.2'
gem 'flipper-active_record', '~> 1.2', '>= 1.2.2'
gem 'flipper-ui', '~> 1.2', '>= 1.2.2'
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'rack-cors', '~> 2.0', '>= 2.0.1'
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
gem 'lograge', '~> 0.14.0'
gem 'oj', '~> 3.16', '>= 3.16.3'
gem 'omniauth', '~> 2.1', '>= 2.1.1'
gem 'pagy', '~> 7.0', '>= 7.0.8'
gem 'pundit', '~> 2.3'
gem 'whenever', '~> 1.0'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'
gem 'rswag-api', '~> 2.11.0'
gem 'rswag-ui', '~> 2.11.0'
gem 'devise', '~> 4.9.3'
gem "devise_token_auth", ">= 1.2.0", git: "https://github.com/lynndylanhurley/devise_token_auth"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'sprockets', '~> 4.2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'annotate', '~> 3.2', '>= 3.0.3'
  gem 'dotenv-rails', '~> 2.8.1'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'pry-byebug', '~> 3.9', platform: :mri
  gem 'pry-rails', '~> 0.3.9'
end

group :test do
  gem 'rspec-openapi', '~> 0.11.0'
  gem 'rspec-rails'
  gem 'rswag-specs'
  gem 'faker', '~> 3.2'
  gem 'knapsack', '~> 4.0'
  gem 'octokit', '~> 8.0'
  gem 'parallel_tests', '~> 4.3'
  gem 'pg_query', '~> 5.1'
  gem 'prosopite', '~> 1.4.1'
  gem 'rspec-retry', '~> 0.6.2'
  gem 'shoulda-matchers', '~> 6.1'
  gem 'simplecov', '~> 0.22.0', require: false
  gem 'webmock', '~> 3.23'
end

group :development do
  gem 'better_errors', '~> 2.10'
  gem 'binding_of_caller', '~> 1.0'
  gem 'brakeman', '~> 6.1', '>= 6.1.2'
  gem 'i18n-tasks', '~> 1.0.13'
  gem 'listen', '~> 3.9'
  gem 'rails_best_practices', '~> 1.23', '>= 1.23.2'
  gem 'reek', '~> 6.3'
  gem 'rubocop', '~> 1.61', require: false
  gem 'rubocop-factory_bot', '~> 2.25', require: false
  gem 'rubocop-performance', '~> 1.20.2', require: false
  gem 'rubocop-rails', '~> 2.23.1', require: false
  gem 'rubocop-rake', '~> 0.6.0', require: false
  gem 'rubocop-rspec', '~> 2.25', require: false
  gem 'spring', '~> 4.1.3'
end
